// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    MyTest: typeof import('./src/components/test/MyTest.vue')['default']
    MyTest01: typeof import('./src/components/test/MyTest01.vue')['default']
    MyTest02: typeof import('./src/components/test/MyTest02.vue')['default']
    MyTest03: typeof import('./src/components/test/MyTest03.vue')['default']
    MyTest04: typeof import('./src/components/test/MyTest04.vue')['default']
    MyTest05: typeof import('./src/components/test/MyTest05.vue')['default']
    MyTest06: typeof import('./src/components/test/MyTest06.vue')['default']
    MyTest07: typeof import('./src/components/test/MyTest07.vue')['default']
    MyTest08: typeof import('./src/components/test/MyTest08.vue')['default']
    MyTest09: typeof import('./src/components/test/MyTest09.vue')['default']
    PaymentPage: typeof import('./src/components/PaymentPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Success: typeof import('./src/components/Success.vue')['default']
  }
}
